[build]
  publish = "."
  command = "echo 'No build step required'"

# ルートアクセス時のリダイレクト
[[redirects]]
  from = "/"
  to = "/fukuoka/2025/tesshie_vtryo_night"
  status = 302

# 福岡イベント用のリダイレクト設定
[[redirects]]
  from = "/fukuoka/2025/tesshie_vtryo_night"
  to = "/fukuoka/2025/tesshie_vtryo_night/index.html"
  status = 200

[[redirects]]
  from = "/fukuoka/2025/tesshie_vtryo_night/*"
  to = "/fukuoka/2025/tesshie_vtryo_night/:splat"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"